package com.yunfei.cultural.entity;

import java.util.Date;

public class TCulturalPeopleTw {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.profession_code
     *
     * @mbg.generated
     */
    private String professionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.representative_works
     *
     * @mbg.generated
     */
    private String representativeWorks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.resume
     *
     * @mbg.generated
     */
    private String resume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.lifetime
     *
     * @mbg.generated
     */
    private String lifetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.head_url
     *
     * @mbg.generated
     */
    private String headUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_people_tw.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.id
     *
     * @return the value of t_cultural_people_tw.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.id
     *
     * @param id the value for t_cultural_people_tw.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.name
     *
     * @return the value of t_cultural_people_tw.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.name
     *
     * @param name the value for t_cultural_people_tw.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.area_code
     *
     * @return the value of t_cultural_people_tw.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.area_code
     *
     * @param areaCode the value for t_cultural_people_tw.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.sex
     *
     * @return the value of t_cultural_people_tw.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.sex
     *
     * @param sex the value for t_cultural_people_tw.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.age
     *
     * @return the value of t_cultural_people_tw.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.age
     *
     * @param age the value for t_cultural_people_tw.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.profession_code
     *
     * @return the value of t_cultural_people_tw.profession_code
     *
     * @mbg.generated
     */
    public String getProfessionCode() {
        return professionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.profession_code
     *
     * @param professionCode the value for t_cultural_people_tw.profession_code
     *
     * @mbg.generated
     */
    public void setProfessionCode(String professionCode) {
        this.professionCode = professionCode == null ? null : professionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.representative_works
     *
     * @return the value of t_cultural_people_tw.representative_works
     *
     * @mbg.generated
     */
    public String getRepresentativeWorks() {
        return representativeWorks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.representative_works
     *
     * @param representativeWorks the value for t_cultural_people_tw.representative_works
     *
     * @mbg.generated
     */
    public void setRepresentativeWorks(String representativeWorks) {
        this.representativeWorks = representativeWorks == null ? null : representativeWorks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.resume
     *
     * @return the value of t_cultural_people_tw.resume
     *
     * @mbg.generated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.resume
     *
     * @param resume the value for t_cultural_people_tw.resume
     *
     * @mbg.generated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.lifetime
     *
     * @return the value of t_cultural_people_tw.lifetime
     *
     * @mbg.generated
     */
    public String getLifetime() {
        return lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.lifetime
     *
     * @param lifetime the value for t_cultural_people_tw.lifetime
     *
     * @mbg.generated
     */
    public void setLifetime(String lifetime) {
        this.lifetime = lifetime == null ? null : lifetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.job
     *
     * @return the value of t_cultural_people_tw.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.job
     *
     * @param job the value for t_cultural_people_tw.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.head_url
     *
     * @return the value of t_cultural_people_tw.head_url
     *
     * @mbg.generated
     */
    public String getHeadUrl() {
        return headUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.head_url
     *
     * @param headUrl the value for t_cultural_people_tw.head_url
     *
     * @mbg.generated
     */
    public void setHeadUrl(String headUrl) {
        this.headUrl = headUrl == null ? null : headUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.create_time
     *
     * @return the value of t_cultural_people_tw.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.create_time
     *
     * @param createTime the value for t_cultural_people_tw.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_people_tw.update_time
     *
     * @return the value of t_cultural_people_tw.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_people_tw.update_time
     *
     * @param updateTime the value for t_cultural_people_tw.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}