package com.yunfei.cultural.entity;

import java.util.Date;

public class TCulturalOrgan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.resume
     *
     * @mbg.generated
     */
    private String resume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.set_up_time
     *
     * @mbg.generated
     */
    private Date setUpTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.possess_by
     *
     * @mbg.generated
     */
    private String possessBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.Incumbent
     *
     * @mbg.generated
     */
    private String incumbent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.nature
     *
     * @mbg.generated
     */
    private String nature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.pic_url
     *
     * @mbg.generated
     */
    private String picUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_organ.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.id
     *
     * @return the value of t_cultural_organ.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.id
     *
     * @param id the value for t_cultural_organ.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.name
     *
     * @return the value of t_cultural_organ.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.name
     *
     * @param name the value for t_cultural_organ.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.resume
     *
     * @return the value of t_cultural_organ.resume
     *
     * @mbg.generated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.resume
     *
     * @param resume the value for t_cultural_organ.resume
     *
     * @mbg.generated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.set_up_time
     *
     * @return the value of t_cultural_organ.set_up_time
     *
     * @mbg.generated
     */
    public Date getSetUpTime() {
        return setUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.set_up_time
     *
     * @param setUpTime the value for t_cultural_organ.set_up_time
     *
     * @mbg.generated
     */
    public void setSetUpTime(Date setUpTime) {
        this.setUpTime = setUpTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.possess_by
     *
     * @return the value of t_cultural_organ.possess_by
     *
     * @mbg.generated
     */
    public String getPossessBy() {
        return possessBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.possess_by
     *
     * @param possessBy the value for t_cultural_organ.possess_by
     *
     * @mbg.generated
     */
    public void setPossessBy(String possessBy) {
        this.possessBy = possessBy == null ? null : possessBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.Incumbent
     *
     * @return the value of t_cultural_organ.Incumbent
     *
     * @mbg.generated
     */
    public String getIncumbent() {
        return incumbent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.Incumbent
     *
     * @param incumbent the value for t_cultural_organ.Incumbent
     *
     * @mbg.generated
     */
    public void setIncumbent(String incumbent) {
        this.incumbent = incumbent == null ? null : incumbent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.nature
     *
     * @return the value of t_cultural_organ.nature
     *
     * @mbg.generated
     */
    public String getNature() {
        return nature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.nature
     *
     * @param nature the value for t_cultural_organ.nature
     *
     * @mbg.generated
     */
    public void setNature(String nature) {
        this.nature = nature == null ? null : nature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.pic_url
     *
     * @return the value of t_cultural_organ.pic_url
     *
     * @mbg.generated
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.pic_url
     *
     * @param picUrl the value for t_cultural_organ.pic_url
     *
     * @mbg.generated
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.create_time
     *
     * @return the value of t_cultural_organ.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.create_time
     *
     * @param createTime the value for t_cultural_organ.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_organ.update_time
     *
     * @return the value of t_cultural_organ.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_organ.update_time
     *
     * @param updateTime the value for t_cultural_organ.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}