package com.yunfei.cultural.entity;

public class TCulturalSpecialistSh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.area_code
     *
     * @mbg.generated
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.age
     *
     * @mbg.generated
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.profession_code
     *
     * @mbg.generated
     */
    private String professionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.representative_works
     *
     * @mbg.generated
     */
    private String representativeWorks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.resume
     *
     * @mbg.generated
     */
    private String resume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.lifetime
     *
     * @mbg.generated
     */
    private String lifetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cultural_specialist_sh.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.id
     *
     * @return the value of t_cultural_specialist_sh.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.id
     *
     * @param id the value for t_cultural_specialist_sh.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.name
     *
     * @return the value of t_cultural_specialist_sh.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.name
     *
     * @param name the value for t_cultural_specialist_sh.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.area_code
     *
     * @return the value of t_cultural_specialist_sh.area_code
     *
     * @mbg.generated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.area_code
     *
     * @param areaCode the value for t_cultural_specialist_sh.area_code
     *
     * @mbg.generated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.sex
     *
     * @return the value of t_cultural_specialist_sh.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.sex
     *
     * @param sex the value for t_cultural_specialist_sh.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.age
     *
     * @return the value of t_cultural_specialist_sh.age
     *
     * @mbg.generated
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.age
     *
     * @param age the value for t_cultural_specialist_sh.age
     *
     * @mbg.generated
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.profession_code
     *
     * @return the value of t_cultural_specialist_sh.profession_code
     *
     * @mbg.generated
     */
    public String getProfessionCode() {
        return professionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.profession_code
     *
     * @param professionCode the value for t_cultural_specialist_sh.profession_code
     *
     * @mbg.generated
     */
    public void setProfessionCode(String professionCode) {
        this.professionCode = professionCode == null ? null : professionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.representative_works
     *
     * @return the value of t_cultural_specialist_sh.representative_works
     *
     * @mbg.generated
     */
    public String getRepresentativeWorks() {
        return representativeWorks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.representative_works
     *
     * @param representativeWorks the value for t_cultural_specialist_sh.representative_works
     *
     * @mbg.generated
     */
    public void setRepresentativeWorks(String representativeWorks) {
        this.representativeWorks = representativeWorks == null ? null : representativeWorks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.resume
     *
     * @return the value of t_cultural_specialist_sh.resume
     *
     * @mbg.generated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.resume
     *
     * @param resume the value for t_cultural_specialist_sh.resume
     *
     * @mbg.generated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.lifetime
     *
     * @return the value of t_cultural_specialist_sh.lifetime
     *
     * @mbg.generated
     */
    public String getLifetime() {
        return lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.lifetime
     *
     * @param lifetime the value for t_cultural_specialist_sh.lifetime
     *
     * @mbg.generated
     */
    public void setLifetime(String lifetime) {
        this.lifetime = lifetime == null ? null : lifetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cultural_specialist_sh.job
     *
     * @return the value of t_cultural_specialist_sh.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cultural_specialist_sh.job
     *
     * @param job the value for t_cultural_specialist_sh.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }
}