package com.yunfei.cultural.entity;

import java.util.Date;

public class TProfession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.profession_name
     *
     * @mbg.generated
     */
    private String professionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.profession_code
     *
     * @mbg.generated
     */
    private String professionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_profession.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.id
     *
     * @return the value of t_profession.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.id
     *
     * @param id the value for t_profession.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.parent_id
     *
     * @return the value of t_profession.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.parent_id
     *
     * @param parentId the value for t_profession.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.profession_name
     *
     * @return the value of t_profession.profession_name
     *
     * @mbg.generated
     */
    public String getProfessionName() {
        return professionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.profession_name
     *
     * @param professionName the value for t_profession.profession_name
     *
     * @mbg.generated
     */
    public void setProfessionName(String professionName) {
        this.professionName = professionName == null ? null : professionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.profession_code
     *
     * @return the value of t_profession.profession_code
     *
     * @mbg.generated
     */
    public String getProfessionCode() {
        return professionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.profession_code
     *
     * @param professionCode the value for t_profession.profession_code
     *
     * @mbg.generated
     */
    public void setProfessionCode(String professionCode) {
        this.professionCode = professionCode == null ? null : professionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.create_time
     *
     * @return the value of t_profession.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.create_time
     *
     * @param createTime the value for t_profession.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_profession.update_time
     *
     * @return the value of t_profession.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_profession.update_time
     *
     * @param updateTime the value for t_profession.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}