#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  #spring.datasource.useGlobalDataSourceStat: true
  ###############以上为配置druid添加的配置########################################

  redis:
    host: 127.0.0.1
    password:
    port: 6379
    maxWaitMillis: 10000
    maxTotal: 200
    testOnBorrow: true
    testOnReturn: true
    timeout: 3600
    maxIdle: 200

  #添加Thymeleaf配置
  thymeleaf:
    cache: false
    #prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html

  #上传最大支持文件大小和最大请求大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#mybatis配置。
#注：通常，若mybatis配置信息较少，只是针对基本配置无需复杂配置，则只需在application.yml文件中配置即可，否则最好配置在 mybatis-config.xml中
mybatis:
  typeAliasesPackage: com.yunfei.cultural.entity
  mapperLocations: classpath:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml

#控制台打印sql
logging:
  level:
    com:
      example:
        restdemo:
          mapper: DEBUG


ftp:
  ftpIp: 127.0.0.1
  ftpUser: ftpUser
  ftpPass: ftpPass
  ftpServer: ftpServer

