package com.yunfei.cultural.mapper;

import com.yunfei.cultural.entity.TCulturalPeopleTw;

public interface TCulturalPeopleTwMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_people_tw
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_people_tw
     *
     * @mbg.generated
     */
    int insert(TCulturalPeopleTw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_people_tw
     *
     * @mbg.generated
     */
    int insertSelective(TCulturalPeopleTw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_people_tw
     *
     * @mbg.generated
     */
    TCulturalPeopleTw selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_people_tw
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCulturalPeopleTw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_people_tw
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCulturalPeopleTw record);
}