package com.yunfei.cultural.mapper;

import com.yunfei.cultural.entity.TCulturalItem;

public interface TCulturalItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_item
     *
     * @mbg.generated
     */
    int insert(TCulturalItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_item
     *
     * @mbg.generated
     */
    int insertSelective(TCulturalItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_item
     *
     * @mbg.generated
     */
    TCulturalItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCulturalItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCulturalItem record);
}