package com.yunfei.cultural.mapper;

import com.yunfei.cultural.entity.TCulturalOrgan;

import java.util.List;

public interface TCulturalOrganMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_organ
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_organ
     *
     * @mbg.generated
     */
    int insert(TCulturalOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_organ
     *
     * @mbg.generated
     */
    int insertSelective(TCulturalOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_organ
     *
     * @mbg.generated
     */
    TCulturalOrgan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_organ
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCulturalOrgan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_organ
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCulturalOrgan record);

    void saveOrUpdateBitch(List<TCulturalOrgan> culturalOrganList);
}