package com.yunfei.cultural.mapper;

import com.yunfei.cultural.entity.TCulturalSpecialistSh;

public interface TCulturalSpecialistShMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_specialist_sh
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_specialist_sh
     *
     * @mbg.generated
     */
    int insert(TCulturalSpecialistSh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_specialist_sh
     *
     * @mbg.generated
     */
    int insertSelective(TCulturalSpecialistSh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_specialist_sh
     *
     * @mbg.generated
     */
    TCulturalSpecialistSh selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_specialist_sh
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCulturalSpecialistSh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_specialist_sh
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCulturalSpecialistSh record);
}