package com.yunfei.cultural.mapper;

import com.yunfei.cultural.entity.TCulturalFamousHt;

public interface TCulturalFamousHtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_famous_ht
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_famous_ht
     *
     * @mbg.generated
     */
    int insert(TCulturalFamousHt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_famous_ht
     *
     * @mbg.generated
     */
    int insertSelective(TCulturalFamousHt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_famous_ht
     *
     * @mbg.generated
     */
    TCulturalFamousHt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_famous_ht
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCulturalFamousHt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cultural_famous_ht
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCulturalFamousHt record);
}