package com.yunfei.cultural.mapper;

import com.yunfei.cultural.entity.TDict;

import java.util.List;

public interface TDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int insert(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int insertSelective(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    TDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TDict record);

    List<TDict> selectAll();

    List<TDict> selectByType(String type);
}